services:

  omeka-s:
    build: ./
    networks:
      - my-network
    ports:
      - "9014:80"
    volumes:
      - ./files/:/var/www/html/flandrica/files/
      - ./config/:/var/www/html/flandrica/config/
    restart: "no"

networks:
  my-network:
    external:
      name: dev-network    