<section class="section text-columns">
  <div class="container">
    <?php if($block->dataValue('title')):?>
      <h3 class="title is-3"><?= $block->dataValue('title');?></h3>
    <?php endif;?>
    <div class="row">
      <?php for($i = 1; $i <= 3; $i++): ?>
        <?php if($block->dataValue('title'.$i)):?>
          <?php if($block->dataValue('title3') != ""): ?>
            <div class="col-xl-4 col-md-6 col-xs-12">
          <?php else: ?>
            <?php if($i == 1):?>
              <div class="col-xl-<?=$block->dataValue('layout');?> col-md-6 col-xs-12">
            <?php else:?>
              <?php $newNumber = 12 - $block->dataValue('layout'); ?>
              <div class="col-xl-<?= $newNumber;?> col-md-6 col-xs-12">
            <?php endif;?>  
          <?php endif; ?>     
          <div class="card card-gray">
            <div class="card-body">
                <h2 class="">
                  <?php if($block->dataValue('link'.$i)):?>
                    <a class="is-white" href="<?= $block->dataValue('link'.$i);?>"><?= $block->dataValue('title'.$i);?></a>
                  <?php else:?>
                    <?= $block->dataValue('title'.$i);?>
                  <?php endif;?>
                </h2>
                <?= $block->dataValue('text'.$i);?>
                <?php if($block->dataValue('link'.$i) && $block->dataValue('linktext'.$i)):?>
                    <a class="card-footer-item is-family-secondary" href="<?= $block->dataValue('link'.$i);?>">
                    <?= $block->dataValue('linktext'.$i);?></a>
                <?php endif;?>
            </div>
          </div>
        </div>
        <?php endif;?>
      <?php endfor; ?>
    </div>
  </div>
</section>
